export const APP = {
  STATE_LOADING: 'APP_STATE_LOADING',
  STATE_ERROR: 'APP_STATE_ERROR'
}

export const AUTH = {
  LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
  LOGIN_RESET: 'AUTH_LOGIN_RESET',

  UPDATE_CREDENTIAL: 'AUTH_UPDATE_CREDENTIAL',

  REGISTER_REQUEST: 'AUTH_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  REGISTER_ERROR: 'AUTH_REGISTER_ERROR',
  REGISTER_RESET: 'AUTH_REGISTER_RESET',

  ACTIVATION_REQUEST: 'AUTH_ACTIVATION_REQUEST',
  ACTIVATION_SUCCESS: 'AUTH_ACTIVATION_SUCCESS',
  ACTIVATION_ERROR: 'AUTH_ACTIVATION_ERROR',
  ACTIVATION_RESET: 'AUTH_ACTIVATION_RESET',
}

export const PROFILE = {
  INFO_REQUEST: 'PROFILE_INFO_REQUEST',
  INFO_SUCCESS: 'PROFILE_INFO_SUCCESS',
  INFO_ERROR: 'PROFILE_INFO_ERROR',
  INFO_RESET: 'PROFILE_INFO_RESET',

  BALANCE_REQUEST: 'PROFILE_BALANCE_REQUEST',
  BALANCE_SUCCESS: 'PROFILE_BALANCE_SUCCESS',
  BALANCE_ERROR: 'PROFILE_BALANCE_ERROR',
  BALANCE_RESET: 'PROFILE_BALANCE_RESET',

  UPDATE_REQUEST: 'PROFILE_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'PROFILE_UPDATE_SUCCESS',
  UPDATE_ERROR: 'PROFILE_UPDATE_ERROR',
  UPDATE_RESET: 'PROFILE_UPDATE_RESET',

  CHANGE_PASSWORD_REQUEST: 'PROFILE_CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS: 'PROFILE_CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_ERROR: 'PROFILE_CHANGE_PASSWORD_ERROR',
  CHANGE_PASSWORD_RESET: 'PROFILE_CHANGE_PASSWORD_RESET'
}

export const PRODUCT = {
  ALL_REQUEST: 'PRODUCT_ALL_REQUEST',
  ALL_SUCCESS: 'PRODUCT_ALL_SUCCESS',
  ALL_ERROR: 'PRODUCT_ALL_ERROR',
  ALL_RESET: 'PRODUCT_ALL_RESET',

  BANNER_REQUEST: 'PRODUCT_BANNER_REQUEST',
  BANNER_SUCCESS: 'PRODUCT_BANNER_SUCCESS',
  BANNER_ERROR: 'PRODUCT_BANNER_ERROR',
  BANNER_RESET: 'PRODUCT_BANNER_RESET'
}

export const HISTORY = {
  PERIOD_REQUEST: 'HISTORY_PERIOD_REQUEST',
  PERIOD_SUCCESS: 'HISTORY_PERIOD_SUCCESS',
  PERIOD_ERROR: 'HISTORY_PERIOD_ERROR',
  PERIOD_RESET: 'HISTORY_PEROID_RESET',

  LAST_TRANSACTION_REQUEST: 'HISTORY_LAST_TRANSACTION_REQUEST',
  LAST_TRANSACTION_SUCCESS: 'HISTORY_LAST_TRANSACTION_SUCCESS',
  LAST_TRANSACTION_ERROR: 'HISTORY_LAST_TRANSACTION_ERROR',
  LAST_TRANSACTION_RESET: 'HISTORY_LAST_TRANSACTION_RESET',

  LAST_TOPUP_REQUEST: 'HISTORY_LAST_TOPUP_REQUEST',
  LAST_TOPUP_SUCCESS: 'HISTORY_LAST_TOPUP_SUCCESS',
  LAST_TOPUP_ERROR: 'HISTORY_LAST_TOPUP_ERROR',
  LAST_TOPUP_RESET: 'HISTORY_LAST_TOPUP_RESET',
}

export const TRANSACTION = {
  TOPUP_TYPE_REQUEST: 'TRANSACTION_TOPUP_TYPE_REQUEST',
  TOPUP_TYPE_SUCCESS: 'TRANSACTION_TOPUP_TYPE_SUCCESS',
  TOPUP_TYPE_ERROR: 'TRANSACTION_TOPUP_TYPE_ERROR',
  TOPUP_TYPE_RESET: 'TRANSACTION_TOPUP_TYPE_RESET',

  TOPUP_ACCOUNT_REQUEST: 'TRANSACTION_TOPUP_ACCOUNT_REQUEST',
  TOPUP_ACCOUNT_SUCCESS: 'TRANSACTION_TOPUP_ACCOUNT_SUCCESS',
  TOPUP_ACCOUNT_ERROR: 'TRANSACTION_TOPUP_ACCOUNT_ERROR',
  TOPUP_ACCOUNT_RESET: 'TRANSACTION_TOPUP_ACCOUNT_RESET',

  TOPUP_REQUEST: 'TRANSACTION_TOPUP_REQUEST',
  TOPUP_SUCCESS: 'TRANSACTION_TOPUP_SUCCESS',
  TOPUP_ERROR: 'TRANSACTION_TOPUP_ERROR',
  TOPUP_RESET: 'TRANSACTION_TOPUP_RESET',

  TOPUP_TIME_SET: 'TRANSACTION_TOPUP_TIME_SET',
  TOPUP_TIME_RESET: 'TRANSACTION_TOPUP_TIME_RESET',

  PAYMENT_REQUEST: 'TRANSACTION_PAYMENT_REQUEST',
  PAYMENT_SUCCESS: 'TRANSACTION_PAYMENT_SUCCESS',
  PAYMENT_ERROR: 'TRANSACTION_PAYMENT_ERROR',
  PAYMENT_RESET: 'TRANSACTION_PAYMENT_RESET',
}