export const APP = {
  STATE_LOADING: 'APP_STATE_LOADING',
  STATE_ERROR: 'APP_STATE_ERROR'
}

export const AUTH = {
  LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
  LOGIN_RESET: 'AUTH_LOGIN_RESET'
}

export const PROFILE = {
  INFO_REQUEST: 'PROFILE_INFO_REQUEST',
  INFO_SUCCESS: 'PROFILE_INFO_SUCCESS',
  INFO_ERROR: 'PROFILE_INFO_ERROR',
  INFO_RESET: 'PROFILE_INFO_RESET',

  BALANCE_REQUEST: 'PROFILE_BALANCE_REQUEST',
  BALANCE_SUCCESS: 'PROFILE_BALANCE_SUCCESS',
  BALANCE_ERROR: 'PROFILE_BALANCE_ERROR',
  BALANCE_RESET: 'PROFILE_BALANCE_RESET',

  UPDATE_REQUEST: 'PROFILE_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'PROFILE_UPDATE_SUCCESS',
  UPDATE_ERROR: 'PROFILE_UPDATE_ERROR',
  UPDATE_RESET: 'PROFILE_UPDATE_RESET',

  CHANGE_PASSWORD_REQUEST: 'PROFILE_CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS: 'PROFILE_CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_ERROR: 'PROFILE_CHANGE_PASSWORD_ERROR',
  CHANGE_PASSWORD_RESET: 'PROFILE_CHANGE_PASSWORD_RESET'
}

export const PRODUCT = {
  ALL_REQUEST: 'PRODUCT_ALL_REQUEST',
  ALL_SUCCESS: 'PRODUCT_ALL_SUCCESS',
  ALL_ERROR: 'PRODUCT_ALL_ERROR',
  ALL_RESET: 'PRODUCT_ALL_RESET'
}